### ISSUE TITLE
Can't make API return a function's callback

### ISSUE THREAD

**Issue by luandro** [claudiajs/claudia-api-builder#14]
I'm trying to use the claudia-api-builder along side [woocommerce-api](https://github.com/woothemes/wc-api-node). No matter how I try to do organize my code, the Lambda endpoint returns me the first call: `WooCommerce.get()` and not it's callback, which contains the response data (`formatedData`).

Here's the code:

```
api.get('/products', (req, res) => {
  const WooCommerce = new WooCommerceAPI({
    url: req.env.configUrl,
    consumerKey: req.env.configConsumerKey,
    consumerSecret: req.env.configConsumerSecret,
  });
  
  const promise = Promise.resolve(
    WooCommerce.get('products', (err, data, response) => {
      if(data.statusCode === 200) {
        const formatedData = JSON.parse(response)
        return formatedData;
      } else {
        return response;
      }
    })
  );

  return promise.then((res) => {
    return res
  });
});
```

How should I organize the functions in order to have the API return the callback of `WooCommerce.get()`?

**Comment by gojko** [comment]
you're immediately resolving the promise on line 6, that's why it's returning like that. I don't know anything about WooCommerce api, but it seems to be using the standard NodeJS callbacks. You'll need to make those into a promise. Using BlueBird, you can do something like 

```
var promisedWoo = Promise.promisifyAll(WooCommerce);
```

then later use 

```
return promisedWoo.getAsync(....)
```

if you don't want to use bluebird, check out https://www.npmjs.com/package/denodeify

**Comment by dancingshell** [comment]
for anyone else stuck on this, node 4.3 has global promises built in:

```js
return new Promise(( resolve, reject ) => {
  return yourAsyncCall( withParams, function yourCallback( err, data) {
    if (err) {
      return reject( err );
    }
    
    return resolve( data );
  });
});
```
