### ISSUE TITLE
Handle files upload

### ISSUE THREAD

**Issue by rafaelamorim** [claudiajs/claudia-api-builder#2]
Provide a way, along with request objects to deal with file uploads (from api to a bucket).

AWSOME job you did here by the way! ;)

**Comment by gojko** [comment]
Hi,

I'm not entirely sure what you are proposing - can you explain it a bit more? An API can upload to an S3 Bucket using the normal S3 APIs already. Check out https://github.com/claudiajs/example-projects/tree/master/s3-file-processing - the `convert.js` module is using the S3 API to upload a file back to the bucket.

**Comment by rafaelamorim** [comment]
As we are using a single endpoint for our api (API Gateway with custom domain) we have a route where users can POST stories.

The POST params structures are: title, text, image.

So what i'm proposing it's a way to handle a file to be passed as a param, and then uploaded to a s3 bucket.

**Comment by gojko** [comment]
ah, ok. I understand. We do something very similar by letting people upload to S3 with a predefined URL, so we can limit the size and content types, then the form post just contains the S3 key. 

I guess to handle your case, we just need an additional template for form/multipart. shouldn't be too difficult to do.

**Comment by rafaelamorim** [comment]
That's it! :+1: 
Thanks for this awesome project.

**Comment by gojko** [comment]
can you share the input template you're using at the moment, so I can massage it in with the rest?

**Comment by gojko** [comment]
i'm closing this due to lack of response; if anyone wants to pick this up in the future, please reopen the issue.

**Comment by alxpereira** [comment]
Hi @gojko, 
I'm really interested to build a claudiajs driver on our framework 
https://www.blockbase.run/en/

However, i'm missing this feature (file upload using the rest API methods POST/PUT), that would be useful...

Can you up ?

**Comment by gojko** [comment]
@alxpereira please use the [project chat channel](https://gitter.im/claudiajs/claudia) for discussions, we use github issues for bugs only

**Comment by keesey** [comment]
I'm sorry this was closed, as I find myself needing to handle `multipart/form-data` requests.

**Comment by dmackinn** [comment]
@keesey did you ever sort it out? I've been trying to figure out multipart/form-data with claudia as well
