### ISSUE TITLE
Support for binary content types

### ISSUE THREAD

**Issue by bendemboski** [claudiajs/claudia-api-builder#27]
API gateway recently [added support for binary content types](https://aws.amazon.com/blogs/compute/binary-support-for-api-integrations-with-amazon-api-gateway/). It would be really super awesome if claudia-api-builder could support this as well!

**Comment by gojko** [comment]
Hi,

We use github issues only for bugs. for feature suggestions and general discussion, please use the [gitter chat channel](https://gitter.im/claudiajs/claudia)
