### ISSUE TITLE
Premature Exit while using Async.js with no results

### ISSUE THREAD

**Issue by ltyu** [claudiajs/claudia-api-builder#33]
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

---

* Expected behaviour:
Results of a mongoose .find call

* What actually happens:
Nothing.  Cloudwatch logs show:
`START RequestId: dc0bc7a1-262e-11e7-b0af-8f68d1af4f11 Version: $LATEST
END RequestId: dc0bc7a1-262e-11e7-b0af-8f68d1af4f11
REPORT RequestId: dc0bc7a1-262e-11e7-b0af-8f68d1af4f11	Duration: 136.11 ms	Billed Duration: 200 ms Memory Size: 128 MB	Max Memory Used: 44 MB	`

* Link to a minimal, executable project that demonstrates the problem:
My only "route"
https://repl.it/HTEz

I am running lambda with node 6.1

**Comment by gojko** [comment]
it looks as if your function is not returning a promise, so this is not a bug. return a promise to make the handler wait for completion. if you'd like to contribute a code change to api builder to support async in addition to promises, we're open to that.

**Comment by ltyu** [comment]
Thanks for your response. Does that mean the async operation isn't running at all or is it because that the async.waterfall function isn't returning a promise?
