### ISSUE TITLE
Add 'Access-Control-Allow-Origin' header to Authorizer's error responses

### ISSUE THREAD

**Issue by anton-107** [claudiajs/claudia-api-builder#37]
When using Cognito Authorizer, I'm hitting an endpoint being Unauthorized, browser throws the following error: 

"No 'Access-Control-Allow-Origin' header is present on the requested resource" 

This can be solved in API Gateway Console by setting a 'Access-Control-Allow-Origin' header in 'Gateway responses' > 'Unauthorized' > 'Response header'

Would be great if this header can be set by ClaudiaJS automatically (probably it's a good idea to set it on other responses as well).

**Comment by gojko** [comment]
this is implemented, you can set [custom responses](https://github.com/claudiajs/claudia-api-builder/blob/master/docs/customise-responses.md#api-gateway-responses) from claudia-api-builder 2.6.0 onwards.

**Comment by gojko** [comment]
this is now on NPM, as version v3.0.0
