### ISSUE TITLE
Use subresources for routing

### ISSUE THREAD

**Issue by xonev** [claudiajs/claudia-api-builder#4]
I have not been able to figure out a way to set up a nested resource for e.g. "/greet/me". Is there a way to do this or is it a missing feature?

**Comment by gojko** [comment]
that's still missing. I'm planning to add that over the next few days.

**Comment by gojko** [comment]
this should now be possible, with https://github.com/claudiajs/claudia/commit/cf597c6888b92d935192e0877f174bcd8d2d2a6f - version 1.0.8 is on NPM, please try it and let me know if it does what you need.
