### ISSUE TITLE
Handling dynamic path variables when running locally

### ISSUE THREAD

**Issue by robertkeizer** [claudiajs/claudia-api-builder#50]
Would be nice if there was a standard way to have dynamic paths working locally, or some documentation about it not working in certain environments.

The functionality I'm talking about is [here](https://github.com/claudiajs/example-projects/blob/fd69a5bbea21854dd585e97909c95b13ddfd8baa/web-api-generic-handlers/web.js#L12), with the lines starting right around [here](https://github.com/claudiajs/claudia-api-builder/blob/337a1a877a2f3bcfdd34cb643b9e2a0e5d270772/src/api-builder.js#L200) making this functionality impossible.

**Comment by gojko** [comment]
Hi, thanks for the suggestion. we use github issues only for bugs, general discussion should go to the gitter chat channel
