### ISSUE TITLE
[Improvement] Use Method-Aware Status Codes

### ISSUE THREAD

**Issue by aaronjameslang** [claudiajs/claudia-api-builder#52]
Currently, the default success code is 200. It could be 201 Created for POST, 204 No Content for PUT and DELETE, etc. 

This would encourage apps to use the correct codes, and save users having to configure this on every route themselves.

Does this sounds like a good idea?

https://github.com/claudiajs/claudia-api-builder/blob/master/src/api-builder.js#L69

**Comment by gojko** [comment]
hi, let's please move this discussion to the gitter chat channel, we use github issues for bug reports only
