### ISSUE TITLE
CORS with Cognito Authorizer

### ISSUE THREAD

**Issue by LukeMizuhashi** [claudiajs/claudia-api-builder#57]
Can anyone show me a snippet of code that demonstrates an endpoint that responds to GET requests, requires an Authorization header, uses Cognito as an authorizer, and allows CORS requests from exactly two domain names?

The documentation on these things seems to be out of date, possibly. When I leave Cognito authentication out, CORS works just fine for either all domains or exactly one. When I add a Cognito Authorizer, CORS headers are present on OPTIONS responses, but not any of the other HTTP verbs. 

No combination of static endpoint configuration object, ApiResponse object--one or both together--seems to work as expected when both CORS and authentication are required.

**Comment by aaronjameslang** [comment]
You might have better luck asking here: https://gitter.im/claudiajs/claudia
