### ISSUE TITLE
Add options to `ApiResponse`

### ISSUE THREAD

**Issue by gilles-crealp** [claudiajs/claudia-api-builder#61]
For the moment, it's not possible to pass `contentHandling: 'CONVERT_TO_BINARY'` to a new `ApiResponse`.

It could be a good option to have the possibility to add some configuration to a new `ApiResponse`.

https://github.com/claudiajs/claudia-api-builder/blob/1071ecc72cd9fdd48834992871eb01c7b17a92f8/src/api-builder.js#L480-L485

**Comment by gojko** [comment]
please use the gitter chat channel for this kind of discussions, we use github issues only for bugs.  https://gitter.im/claudiajs/claudia
