### ISSUE TITLE
A sibling ({uuid}) of this resource already has a variable path part -- only one is allowed

### ISSUE THREAD

**Issue by juanr2001** [claudiajs/claudia-api-builder#62]
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

---

* Expected behaviour:
It should deploy without any problem...
* What actually happens:
- `A sibling ({uuid}) of this resource already has a variable path part -- only one is allowed`

* Link to a minimal, executable project that demonstrates the problem:
 I don't have a sample, but I hope the explanation above is enough.

* Steps to install the project:

* Steps to reproduce the problem:

When run `npm run cl:deploy`, it return the error below.

`A sibling ({uuid}) of this resource already has a variable path part -- only one is allowed`

The router below has a pathParam `id`

```
api.delete("/admin/{hash}/users/{id}", async request => {
  }, responseIndentifier("delete"));

```
However when I remove the pathParam from the above route, I add a pathParam to the route below. When I try to deploy it, it works!!!, WHY?

```
api.delete('/admin/{hash}/users/{user_uuid}/post/{uuid}', async request => {
  }, responseIndentifier('delete'));

```

**Comment by gojko** [comment]
this is a limitation of api gateway, not claudia - we just pass routes in the order you defined them to API GW definitions. check with AWS support why it's rejecting your routes
