### ISSUE TITLE
Authorization with Cognito User Pools and Axios client-side

### ISSUE THREAD

**Issue by willsned** [claudiajs/claudia-api-builder#64]
I'd like to add cognito user pool authorization to my claudia api, but I keep on getting cors errors. My current error is "CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

My back-end uses:
```
var ApiBuilder = require('claudia-api-builder');
app = new ApiBuilder();
app.registerAuthorizer('MyCognitoAuth', {
    providerARNs: [<my user pool Arn>]
});
app.corsHeaders('Content-Type,Authorization,foo,bar');
```

I'm using Vue (axios) for my front-end, with calls that look like
```
const api =  axios.create({
  baseURL: `https://8d0g0s8dmc.execute-api.us-east-2.amazonaws.com/latest`,
  headers: {
    "Access-Control-Allow-Credentials" : true,
    "Access-Control-Allow-Origin": "*",
    'Authorization': localStorage.mtopToken
  }
});
fetchSpots () {
    return api.get('spot')
  },
```

I know I'm incorrectly using corsHeaders wrong.
I would really appreciate it if someone could explain how to do authorization with headers from axios to claudia back-end

I really appreciate any help. Thanks so much!

**Comment by gojko** [comment]
hi - this really isn't the place for such questions; we use github issues for bug reports only. check with axios how to create cors requests, or if you'd like to discuss setting up cors in claudia, use the gitter chat (https://gitter.im/claudiajs/claudia)
