### ISSUE TITLE
Dynamic routing parameters

### ISSUE THREAD

**Issue by marcusoftnet** [claudiajs/claudia-api-builder#7]
Hi guys - love the project. Dead simple to get started with. 

I'd love a simple routing enhancement so that you can catch parameters in the URL. 

```javascript
var ApiBuilder = require("claudia-api-builder");
var api = new ApiBuilder();

api.get("/get/{id}", function (request) {
   return request.id; 
});
```

So if I access this with `/get/123` I'll get `123` back

**Comment by gojko** [comment]
try `request.pathParams.id` - should work already

**Comment by gojko** [comment]
(just name sure you're using the latest API builder, so it can handle sub-routes). I've updated the  [Request Object docs])https://github.com/claudiajs/claudia-api-builder#the-request-object) to show the path params, and added another example to the [web api](https://github.com/claudiajs/example-projects/blob/master/web-api/web.js) project to show how to use them.

**Comment by marcusoftnet** [comment]
Bah! Saw that now. Sorry!

**Comment by gojko** [comment]
no need to be sorry, it wasn't in the docs. it was in the code, though, so this was a nice documentation bug report :)
