### ISSUE TITLE
Documentation: Pont out where claudia looks for credentials

### ISSUE THREAD

**Issue by hitautodestruct** [claudiajs/claudia-api-builder#8]
While going over the guide there is a link pointing to the configuration of the AWS node SDK specifically about how to set up credentials.
On the linked page there are several methods to add credentials to the node sdk. But it is not exactly clear which one Claudia uses for connecting to the api.
Can this be clarified with a sentence: "Claudia uses ~/.sdk/config file" or "Claudia uses a json file in your project"?

Thanks!

**Comment by gojko** [comment]
Huh... I've tried to explain it, but I obviously haven't done a good job, so I'll try to improve it. Meanwhile, Claudia.js **does not look** for credentials. It just uses the Node.js SDK for AWS, which looks for credentials in all those places; that's why it's probably confusing.
